mutation AddItemToCartMutation($cartId:ID!,$quantity:Int!, $productVariantId:ID!){
    cartLinesAdd(
        cartId: $cartId,
        lines: [
            {
                quantity: $quantity,
                merchandiseId: $productVariantId
            }
        ]
    ) {
        cart {
            id
            cost {
                subtotalAmount {
                    amount
                }
                totalAmount {
                    amount
                }
            }
            discountAllocations {
                discountedAmount {
                    amount
                }
            }
        }
        userErrors {
            field
            message
        }
    }
}
