mutation ApplyCouponToCartMutation($cartId:ID!,$coupon:String!) {
    cartDiscountCodesUpdate(
        cartId: $cartId,
        discountCodes: [$coupon]
    ) {
        cart {
            id
            discountCodes {
                code
                applicable
            }
            cost{
                subtotalAmount {
                    amount
                }
                totalAmount{
                    amount
                }
            }
            discountAllocations {
                discountedAmount {
                    amount
                }
            }
        }
        userErrors {
            field
            message
        }
    }
}
