mutation RemoveItemFromCartMutation($cartId:ID!,$lineId:ID!){
    cartLinesRemove(
        cartId: $cartId,
        lineIds: [
            $lineId
        ]
    ) {
        cart {
            id
            cost {
                subtotalAmount {
                    amount
                }
                totalAmount {
                    amount
                }
            }
            discountAllocations {
                discountedAmount {
                    amount
                }
            }
        }
        userErrors {
            field
            message
        }
    }
}
