query GetCouponsQuery {
    discountNodes(first: 10) {
        edges {
            node {
                discount {
                    ... on DiscountCodeBasic {
                        summary
                        codes(first: 5) {
                            edges {
                                node {
                                    code
                                }
                            }
                        }

                    }
                }
            }
        }
    }
}